### ISSUE TITLE
Don't autofix CSS if there no violations found

### ISSUE THREAD

**Issue by ismail-syed** [hudochenkov/stylelint-order#51] opened 2017-11-01 15:56 UTC
👋  The `order/order` rule seems to be creating some unexpected behavior.

I've documented and created a reproducible example here: https://github.com/ismail-syed/stylelint-order-order-bug

tl;dr: 
* `order/order` is applying fixes when it originally never report lint errors
* `/* stylelint-disable order/order */` doesn't work. I suspect this is because the lint errors aren't being reported as expected. 

Thanks for the great plugin!

**Comment by hudochenkov** [comment] 2017-11-01 16:33
Thank you for reporting and created a repository with the reproducible example!

Let me explain why it's happening.

1\. `--fix` is an experimental feature and it currently [ignores](https://stylelint.io/user-guide/cli/#autofixing-errors) `/* stylelint-disable */` when rule support auto fixing and auto fix is enabled.

2\. `stylelint-order` uses `postcss-sorting` for auto fixing. If auto fixing is enabled, then `stylelint-order` won't check violations and just run `postcss-sorting`. They have similar logic, so it's pretty safe to do this. Which is not enough safe as we just found out.

`stylelint-order` doesn't report violations, because [order from your config](https://github.com/Shopify/stylelint-config-shopify/blob/c5406877c6e0f2c10a1c89eb159a39dfb0d72103/rules/order.js#L4) is correct for a provided code. So, with `--fix` `postcss-sorting` kicks in. It puts everything that is defined in config on top of a CSS rule in a defined order and put everything undefined below ordered stuff. So because only variables are defined in your config, it put them on top and everything else — below.

This behavior is not acceptable. I'm going to change `stylelint-order` behavior from described above. It will check for violations, and if there any violation, then it will run `postcss-sorting`. New behavior will be much safer. Also, it will fix a problem described in https://github.com/hudochenkov/stylelint-order/issues/49.

**Comment by hudochenkov** [comment] 2017-12-04 23:19
Fixed in [`0.8.0`](https://github.com/hudochenkov/stylelint-order/releases/tag/0.8.0). Thank you for reporting!

**Closed by hudochenkov** 2017-12-04 23:19 UTC
Labels: wip
