### ISSUE TITLE
CSS not linted inside a Styled Component `css` tag

### ISSUE THREAD

**Issue by caribou-code** [hudochenkov/stylelint-order#93] opened 2019-07-15 20:05 UTC
**Description**

stylelint-order ignores CSS for Styled Components when in a `css` template literal wrapper.

**Example**

_.stylelintrc_
```
{
  "processors": [
    "stylelint-processor-styled-components"
  ],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components",
    "stylelint-config-rational-order"
  ]
}
```

_components/Button/index.style.ts_
```
import styled, { css } from 'styled-components';

interface ButtonStyledProps {
  isDisabled?: boolean;
  isLoading?: boolean;
  variant?: 'dark' | 'light';
}

export const ButtonStyled = styled.button<ButtonStyledProps>`
  ${p => css`
    padding: 0 ${p.theme.button.padding};
    color: ${p.variant === 'dark' && p.theme.button.colorDark};
    color: ${p.variant === 'light' && p.theme.button.colorLight};
    color: ${p.isLoading && 'transparent'};
    font-weight: ${p.theme.button.fontWeight};
    font-size: ${p.theme.button.fontSize};
    font-family: ${p.theme.button.fontFamily};
    line-height: ${p.theme.button.height};
    text-transform: ${p.theme.button.textTransform};
    border-radius: ${p.theme.button.borderRadius};
    cursor: ${(p.isLoading || p.isDisabled) && 'default'};
    opacity: ${p.isDisabled && 0.2};
    pointer-events: ${(p.isLoading || p.isDisabled) && 'none'};
    height: ${p.theme.button.height};
  `}
`;
```

When props are accessed so many times in a styled component, it makes sense to use the wrapping css tag so only 1 function is created. Everything inside there is valid CSS so should be linted, but stylelint-order is not correctly flagging the height property as being in the wrong place. This bug may be a general stylelint bug because other non ordering rules are also not linting styles inside the `css` tag.

**Comment by hudochenkov** [comment] 2019-07-15 21:20
What output do you get?

Do other stylelint rules work? I. e. [`declaration-empty-line-before: "always"`](https://stylelint.io/user-guide/rules/declaration-empty-line-before)?

It might be the case that stylelint just don't parse your file, because you're using TypeScript and stylelint doesn't support it.

**Comment by caribou-code** [comment] 2019-07-16 06:22
Stylelint and the property ordering works fine if I don't use the `css` tag wrapper e.g. if I use inline props like so:

```
export const ButtonStyled = styled.button<ButtonStyledProps>`
    padding: 0 ${p => p.theme.button.padding};
    color: ${p => p.variant === 'dark' && p.theme.button.colorDark};
    font-weight: ${p => p.theme.button.fontWeight};
`;
```
There is a note in the README that says:

`CSS-in-JS styles with template interpolation could be ignored by autofixing to avoid styles corruption.`

Not sure if that has anything to do with it?

**Comment by hudochenkov** [comment] 2019-07-16 07:01
I'll take a look at the problem within the next week or two.

**Comment by caribou-code** [comment] 2019-07-16 07:21
Thanks. I'm starting to think the issue is with stylelint rather than this specific ordering package.

**Comment by hudochenkov** [comment] 2019-07-19 13:11
Could you create a repo with reproducible example, please? I can't reproduce the problem.

**Comment by Evalon** [comment] 2019-07-19 22:50
It's fixed by: https://github.com/gucong3000/postcss-jsx/pull/58

**Comment by caribou-code** [comment] 2019-07-24 11:15
@Evalon Maybe I'm misunderstanding something but I don't see how that PR will fix this problem...

@hudochenkov I'm happy to create an example, but thinking I should maybe create an issue on the main stylelint repo instead, since I think it's all linting that doesn't work in this scenario, not just ordering

**Comment by Evalon** [comment] 2019-07-24 11:47
@caribou-code This helps greatly if you create reproduction repository. Also, if you use latest version of stylelint you don't need "stylelint-processor-styled-components" because styled-components supported out of the box or maybe some features missing?

**Comment by caribou-code** [comment] 2019-07-26 19:09
@hudochenkov @Evalon Sorry for the delay. I've created a public repo with the most basic reproduction of the issue I can do: https://github.com/caribou-code/stylelint-test

Clone it, `npm install` then run `npm run stylelint`.

There are 3 styled components in test/index.style.ts. All have the same properties with `display: block` in the wrong order. Stylelint correctly flags the first 2 as being in the wrong order but not the 3rd. The 3rd one is potentially a technique that could be used to write a substantial amount of CSS.

**Comment by hudochenkov** [comment] 2019-07-26 19:21
As soon as `stylelint-processor-styled-components` disabled everything is works. Stylelint supports CSS-in-JS out of the box, no need for this processor.

**Comment by caribou-code** [comment] 2019-07-26 21:11
Right you are! I've discovered a completely different bug with the main stylelint package as a result of this, but this specific issue can be closed.

**Closed** 2019-07-26 21:35 UTC
